firebase:
  project-id: your-firebase-project-id
  config-path: /path/to/your-service-account.json

jwt:
  secret: super-secret-secret-key #Use for example openssl rand -base64 64 for generation
  expiration: 3600000

cors:
  allowed-origins: "http://localhost:5173"
